### ISSUE TITLE
untar doesnt supports paxheader files

### ISSUE THREAD

**Issue by radare** [poliva/radare-installer#7]
The com.ice.tar should ignore those PaxHeaders files

```
W/System.err( 1260): java.io.IOException: error making directory path '/./PaxHeaders.6768'
W/System.err( 1260):    at com.ice.tar.TarArchive.extractEntry(TarArchive.java:554)
W/System.err( 1260):    at com.ice.tar.TarArchive.extractContents(TarArchive.java:487)
W/System.err( 1260):    at org.radare.installer.MainActivity.unTarGz(MainActivity.java:382)
W/System.err( 1260):    at org.radare.installer.MainActivity$3$1.run(MainActivity.java:246)
W/System.err( 1260):    at java.lang.Thread.run(Thread.java:856)
I/System  ( 1260): Failed to destroy process 1316
I/System  ( 1260): libcore.io.ErrnoException: kill failed: ESRCH (No such process)
I/System  ( 1260):  at libcore.io.Posix.kill(Native Method)
I/System  ( 1260):  at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
I/System  ( 1260):  at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
I/System  ( 1260):  at com.stericson.RootTools.Shell.readOutput(Shell.java:310)
I/System  ( 1260):  at com.stericson.RootTools.Shell.access$1(Shell.java:268)
I/System  ( 1260):  at com.stericson.RootTools.Shell$2.run(Shell.java:259)
I/System  ( 1260):  at java.lang.Thread.run(Thread.java:856)
D/dalvikvm( 1260): GC_CONCURRENT freed 414K, 8% free 6702K/7239K, paused 2ms+2ms
```

**Comment by radare** [comment]
New tarballs are created using 'tar czovf' (the 'o' specifies old ustar format, which is properly supported by ice.tar implementation). But it would be good to show the exception on the app instead of logcat when an exception is thrown. Or at least be able to support those kind of tarballs.

**Comment by radare** [comment]
Those flags seems to be only valid for OSX tar. the linux tarball seems to not be working properly. It would be nice if the app could report an error when having problems uncompressing the tarball
